### PR TITLE
Speed up sim

### PR DESCRIPTION
**Pull request by bjungwirth**

### CODE REVIEW

**Comment by Denwen12** [comment]
What does this merge improve?

**Comment by chanzer0** [comment]
> What does this merge improve?


This will drastically increase the speed at which we can simulate tournament lineups (`python .\main.py <site> sim <field_size> <num_iterations>` command), getting help from a friend of mine (@bjungwirth) who is more knowledgeable of these python data structures.

A few more changes are gonna be made and I'll review them and continue working with jungwirth to improve the effectiveness of this tool

**Comment by Denwen12** [comment]
Gotcha

**Comment by bjungwirth** [comment]
yeah @Denwen12 just trying to speed up the simulation process. still recommend using the optimizer to generate tournament lineups, but the gpp simulator is now able to run 10k sims in under a minute (with a tournament_lineups.csv file) depending on field size. 

also added a new command for filling up the contest with generated lineups if let's say you have 1000 optimized lineups in a contest of 10k size, with match the script will generate the extra 9k lineups for you

**Comment by Denwen12** [comment]
Nice

**Comment by Denwen12** [comment]
Anyway you can add in the config a salary limit for teams 18k for any team
players combined

**Comment by chanzer0** [comment]
> Anyway you can add in the config a salary limit for teams 18k for any team players combined


I am working on adding more config options, however this one to me seems sub-optimal in practice so I'm not sure I'll add it just yet -- I may in the future, but my priorities for now are focusing on the GPP simulator and getting late swap perfected

**Review by chanzer0 — APPROVED** [review]

**Pull request merged**
