### PR TITLE
Update nba_optimizer.py

### PR DESCRIPTION
**Pull request by Denwen12**
Removed old Position settings from lines 198 to 212 to just MPE positions

### CODE REVIEW

**Comment by chanzer0** [comment]
with these rulesets, it works sometimes, but other times will produce an "infeasible lineup" -- basically a lineup that will not be able to fit into the FD roster construction (here we see 2 centers, and not enough positions to fill SF since the SF position is being used as MPE for the SG position).

image

**Comment by Denwen12** [comment]
oh i did not see that cause no error was output on mines

**Comment by chanzer0** [comment]
image
you can see it if you add some print statements in the format_lineups() method

**Comment by Denwen12** [comment]
gotcha hmm 
wondering where the issue is then

**Comment by Denwen12** [comment]
yea i ran more lineups then i see
infeasible
['Ben Simmons', None, None, 'Norman Powell', 'Desmond Bane', 'Jimmy Butler', 'Keegan Murray', 'Bam Adebayo', 'Ivica Zubac']
['Bam Adebayo', 'Ben Simmons', 'Desmond Bane', 'Ivica Zubac', 'Ja Morant', 'Jimmy Butler', 'Keegan Murray', 'Norman Powell', 'Steven Adams']
Bam Adebayo 35.19 ['C', 'PF']
Ben Simmons 30.81 ['PG', 'PF']
Desmond Bane 35.29 ['SG', 'SF']
Ivica Zubac 33.21 ['C']
Ja Morant 48.77 ['PG']
Jimmy Butler 39.41 ['SF', 'PF']
Keegan Murray 31.28 ['SF', 'PF']
Norman Powell 23.8 ['SF', 'SG']
Steven Adams 27.05 ['C']

**Comment by Denwen12** [comment]
10 it didnt show up

**Pull request closed without merging**
